[package]
name = "ghastoolkit-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
clap = { version = "4.5.1", features = ["derive", "env"] }
console = "0.15.8"
dotenv = { version = "0.15.0", features = ["clap"] }
env_logger = "0.11.2"
ghastoolkit = { path = "../core" }
log = "0.4.20"
tokio = { version = "1.36.0", features = ["full"] }
