[package]
name = "ghastoolkit"
version = "0.4.0"

description = "GitHub Advanced Security Toolkit in Rust"
keywords = ["github", "security", "ghas"]
homepage = "https://github.com/GeekMasher/ghastoolkit-rs"
repository = "https://github.com/GeekMasher/ghastoolkit-rs"
documentation = "https://docs.rs/ghastoolkit/latest/ghastoolkit/"

authors = ["GeekMasher"]
license = "MIT"

readme = "../README.md"

rust-version = "1.70"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["async"]

async = ["dep:async-trait", "dep:tokio"]

[dependencies]
anyhow = "1.0.80"
chrono = { version = "0.4.34", features = ["serde"] }
git2 = "0.19.0"
glob = "0.3.1"
log = "0.4.20"
octocrab = "0.38.0"
purl = { version = "0.1.2", features = ["serde"] }
regex = "1.10.3"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
serde_yaml = "0.9.32"
thiserror = "1.0.57"
url = { version = "2.5.0", features = ["serde"] }
walkdir = "2.5.0"
time = "0.3.36"

# Async
async-trait = { version = "0.1.77", optional = true }
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread", "time"], optional = true}

[dev-dependencies]
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread", "time"] }

[[example]]
name = "codeql-packs"
path = "../examples/codeql-packs/src/main.rs"
