[package]
name = "ghastoolkit"
version = "0.1.1"

description = "GitHub Advanced Security Toolkit in Rust"
keywords = ["github", "security", "ghas"]
homepage = "https://github.com/GeekMasher/ghastoolkit-rs"
repository = "https://github.com/GeekMasher/ghastoolkit-rs"

authors = ["GeekMasher"]
license = "MIT"

readme = "../README.md"

rust-version = "1.70"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
async-trait = "0.1.77"
chrono = { version = "0.4.34", features = ["serde"] }
git2 = "0.18.2"
log = "0.4.20"
octocrab = "0.34.1"
regex = "1.10.3"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
serde_yaml = "0.9.32"
thiserror = "1.0.57"
url = { version = "2.5.0", features = ["serde"] }

[dev-dependencies]
tokio = { version = "1.36.0", features = ["macros", "rt-multi-thread", "time"] }
