name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        rust-version: [ stable, beta, nightly ]

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup - Rust Toolchain"
        uses: dtolnay/rust-toolchain@7b1c307e0dcbda6122208f10795a713336a9b35a
        with:
          toolchain: ${{ matrix.rust-version }}

      - name: "Build"
        run: |
          cargo build --workspace

  lint:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup - Rust Toolchain"
        uses: dtolnay/rust-toolchain@7b1c307e0dcbda6122208f10795a713336a9b35a
        with:
          toolchain: stable
          components: clippy,rustfmt

      - run: |
          # cargo clippy --all-targets -- clippy::all

  test:
    runs-on: ubuntu-latest
    needs: [ build ]
    
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup - Rust Toolchain"
        uses: dtolnay/rust-toolchain@7b1c307e0dcbda6122208f10795a713336a9b35a
        with:
          components: clippy,rustfmt
          toolchain: ${{ matrix.rust }}

      - name: Run tests
        run: |
          cargo test --workspace
